// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using borealis_flowers.api.Data;

#nullable disable

namespace borealis_flowers.api.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260521133529_AddServiceCatalogFields")]
    partial class AddServiceCatalogFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("borealis_flowers.api.Data.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstVisit")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMaster")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSpecialist")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastVisit")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SpecialistId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisitorId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpecialistId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("borealis_flowers.api.Data.Models.DateSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWorkingDay")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SpecialistId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpecialistId");

                    b.ToTable("DateSchedules");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20f92d7b-adec-49c3-88b0-374f45f3e728"),
                            Date = new DateTime(2023, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            IsWorkingDay = true,
                            SpecialistId = new Guid("dfe327cd-3efc-42f5-8dfc-f3bce55a49b7")
                        },
                        new
                        {
                            Id = new Guid("249b8b38-2697-45ba-b59d-839f07af4f51"),
                            Date = new DateTime(2023, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            IsWorkingDay = true,
                            SpecialistId = new Guid("dfe327cd-3efc-42f5-8dfc-f3bce55a49b7")
                        },
                        new
                        {
                            Id = new Guid("e039320c-8ed6-4838-bf13-6b05b9bdcb09"),
                            Date = new DateTime(2023, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            IsWorkingDay = true,
                            SpecialistId = new Guid("dfe327cd-3efc-42f5-8dfc-f3bce55a49b7")
                        },
                        new
                        {
                            Id = new Guid("f91ab0ad-fc6d-4079-a542-92f2be259262"),
                            Date = new DateTime(2023, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            IsWorkingDay = true,
                            SpecialistId = new Guid("dfe327cd-3efc-42f5-8dfc-f3bce55a49b7")
                        });
                });

            modelBuilder.Entity("borealis_flowers.api.Data.Models.FloristApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminComment")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Motivation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PortfolioNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("FloristApplications");
                });

            modelBuilder.Entity("borealis_flowers.api.Data.Models.HistoryTimeslot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("FeedbackRequested")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TimeslotId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TimeslotId");

                    b.ToTable("HistoryTimeslots");
                });

            modelBuilder.Entity("borealis_flowers.api.Data.Models.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminComment")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Budget")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("ClientConfirmedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DepartureAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EventStartsAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FloristComment")
                        .HasColumnType("TEXT");

                    b.Property<string>("FloristInventory")
                        .HasColumnType("TEXT");

                    b.Property<string>("FloristMaterials")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderKind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("State");

                    b.Property<double?>("QuoteTotal")
                        .HasColumnType("REAL");

                    b.Property<string>("Resolution")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ResolutionSent")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceTitleSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SpecialistId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Venue")
                        .HasColumnType("TEXT");

                    b.Property<string>("WishNotes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("SpecialistId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("borealis_flowers.api.Data.Models.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EstimatedTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FlowerComposition")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<Guid>("SpecializationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpecializationId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5b385e48-5a16-4575-8290-ee173711840c"),
                            EstimatedTime = 90,
                            Name = "Coloring",
                            Price = 60.0,
                            SpecializationId = new Guid("ff034503-2dad-402a-a7c0-7aa7f2b2d99b")
                        },
                        new
                        {
                            Id = new Guid("1219e0a7-4cbb-4395-a7b8-d4ce3979a9ac"),
                            EstimatedTime = 35,
                            Name = "Haircut",
                            Price = 15.0,
                            SpecializationId = new Guid("ff034503-2dad-402a-a7c0-7aa7f2b2d99b")
                        },
                        new
                        {
                            Id = new Guid("2944556b-ca71-449c-8b2a-0b493b2d3a78"),
                            EstimatedTime = 35,
                            Name = "Mens Hair Cut",
                            Price = 19.0,
                            SpecializationId = new Guid("ff034503-2dad-402a-a7c0-7aa7f2b2d99b")
                        },
                        new
                        {
                            Id = new Guid("ecf67bc9-70f3-4d38-abd6-2e1bbc457756"),
                            EstimatedTime = 60,
                            Name = "Ladies Cut",
                            Price = 60.0,
                            SpecializationId = new Guid("ff034503-2dad-402a-a7c0-7aa7f2b2d99b")
                        },
                        new
                        {
                            Id = new Guid("73e26494-9a6c-43cd-a5f0-486afced5d61"),
                            EstimatedTime = 45,
                            Name = "Makeup",
                            Price = 20.0,
                            SpecializationId = new Guid("7fe3e393-71d2-4385-b775-8617126c6f0f")
                        },
                        new
                        {
                            Id = new Guid("2dfda2c0-3dc6-4937-b52a-fca938ac6a63"),
                            EstimatedTime = 30,
                            Name = "Eyebrows",
                            Price = 20.0,
                            SpecializationId = new Guid("7fe3e393-71d2-4385-b775-8617126c6f0f")
                        });
                });

            modelBuilder.Entity("borealis_flowers.api.Data.Models.ServicePrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SpecialistId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("SpecialistId");

                    b.ToTable("ServicePrice");
                });

            modelBuilder.Entity("borealis_flowers.api.Data.Models.Specialist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<Guid>("SpecializationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpecializationId");

                    b.ToTable("Specialists");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dfe327cd-3efc-42f5-8dfc-f3bce55a49b7"),
                            FullName = "Cecile Hahn",
                            ImgUrl = "https://loremflickr.com/958/958",
                            IsActive = true,
                            SpecializationId = new Guid("ff034503-2dad-402a-a7c0-7aa7f2b2d99b")
                        },
                        new
                        {
                            Id = new Guid("278666b8-3503-47b0-b5f6-7139563dace6"),
                            FullName = "Francisco Gutkowski",
                            ImgUrl = "http://lorempixel.com/640/480/abstract",
                            IsActive = true,
                            SpecializationId = new Guid("ff034503-2dad-402a-a7c0-7aa7f2b2d99b")
                        },
                        new
                        {
                            Id = new Guid("b23a6e06-ce61-4445-be74-0cfc5f0a0729"),
                            FullName = "Waino Rath",
                            ImgUrl = "http://lorempixel.com/640/480/nature",
                            IsActive = true,
                            SpecializationId = new Guid("20df743a-bdfa-48c8-8eee-40ce4a3f3bde")
                        },
                        new
                        {
                            Id = new Guid("5bd8fd04-9613-4c69-85c9-7347572f6289"),
                            FullName = "Emmet Walsh",
                            ImgUrl = "http://lorempixel.com/640/480/sports",
                            IsActive = true,
                            SpecializationId = new Guid("7fe3e393-71d2-4385-b775-8617126c6f0f")
                        },
                        new
                        {
                            Id = new Guid("88639ec4-d834-4788-bce4-05cfce258cce"),
                            FullName = "Odessa Russel",
                            ImgUrl = "http://lorempixel.com/640/480/animals",
                            IsActive = true,
                            SpecializationId = new Guid("d78d53c1-f24a-4d27-86a4-54adaebb3ae5")
                        });
                });

            modelBuilder.Entity("borealis_flowers.api.Data.Models.Specialization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Specialization");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ff034503-2dad-402a-a7c0-7aa7f2b2d99b"),
                            Description = "Hair Specialization",
                            IsActive = true,
                            Name = "Hair"
                        },
                        new
                        {
                            Id = new Guid("20df743a-bdfa-48c8-8eee-40ce4a3f3bde"),
                            Description = "Nail Specialization",
                            IsActive = true,
                            Name = "Nail"
                        },
                        new
                        {
                            Id = new Guid("7fe3e393-71d2-4385-b775-8617126c6f0f"),
                            Description = "Skincare Specialization",
                            IsActive = true,
                            Name = "Skincare"
                        },
                        new
                        {
                            Id = new Guid("d78d53c1-f24a-4d27-86a4-54adaebb3ae5"),
                            Description = "Makeup Specialization",
                            IsActive = true,
                            Name = "Makeup"
                        });
                });

            modelBuilder.Entity("borealis_flowers.api.Data.Models.Timeslot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Available")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DateScheduleId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Time")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DateScheduleId");

                    b.ToTable("Timeslots");
                });

            modelBuilder.Entity("borealis_flowers.api.Data.Models.Customer", b =>
                {
                    b.HasOne("borealis_flowers.api.Data.Models.Specialist", null)
                        .WithMany()
                        .HasForeignKey("SpecialistId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("borealis_flowers.api.Data.Models.DateSchedule", b =>
                {
                    b.HasOne("borealis_flowers.api.Data.Models.Specialist", null)
                        .WithMany("DateSchedules")
                        .HasForeignKey("SpecialistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("borealis_flowers.api.Data.Models.FloristApplication", b =>
                {
                    b.HasOne("borealis_flowers.api.Data.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("borealis_flowers.api.Data.Models.HistoryTimeslot", b =>
                {
                    b.HasOne("borealis_flowers.api.Data.Models.Timeslot", "Timeslot")
                        .WithMany()
                        .HasForeignKey("TimeslotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Timeslot");
                });

            modelBuilder.Entity("borealis_flowers.api.Data.Models.Request", b =>
                {
                    b.HasOne("borealis_flowers.api.Data.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("borealis_flowers.api.Data.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("borealis_flowers.api.Data.Models.Specialist", "Specialist")
                        .WithMany()
                        .HasForeignKey("SpecialistId");

                    b.Navigation("Customer");

                    b.Navigation("Service");

                    b.Navigation("Specialist");
                });

            modelBuilder.Entity("borealis_flowers.api.Data.Models.Service", b =>
                {
                    b.HasOne("borealis_flowers.api.Data.Models.Specialization", "Specialization")
                        .WithMany()
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("borealis_flowers.api.Data.Models.ServicePrice", b =>
                {
                    b.HasOne("borealis_flowers.api.Data.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("borealis_flowers.api.Data.Models.Specialist", "Specialist")
                        .WithMany()
                        .HasForeignKey("SpecialistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Specialist");
                });

            modelBuilder.Entity("borealis_flowers.api.Data.Models.Specialist", b =>
                {
                    b.HasOne("borealis_flowers.api.Data.Models.Specialization", "Specialization")
                        .WithMany()
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("borealis_flowers.api.Data.Models.Timeslot", b =>
                {
                    b.HasOne("borealis_flowers.api.Data.Models.Customer", "Customer")
                        .WithMany("Timeslots")
                        .HasForeignKey("CustomerId");

                    b.HasOne("borealis_flowers.api.Data.Models.DateSchedule", "DateSchedule")
                        .WithMany("Timeslots")
                        .HasForeignKey("DateScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("DateSchedule");
                });

            modelBuilder.Entity("borealis_flowers.api.Data.Models.Customer", b =>
                {
                    b.Navigation("Timeslots");
                });

            modelBuilder.Entity("borealis_flowers.api.Data.Models.DateSchedule", b =>
                {
                    b.Navigation("Timeslots");
                });

            modelBuilder.Entity("borealis_flowers.api.Data.Models.Specialist", b =>
                {
                    b.Navigation("DateSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
